export enum ROUTES {
  ROOT = '',
  APP = 'app',
  AUTH = 'auth',
  SIGN_IN = 'sign-in',
  SIGN_UP = 'sign-up',
  HOME = 'home',
  DASHBOARD = 'dashboard',
  TEACHERS = 'teachers',
  STUDENTS = 'students',
  SETTINGS = 'settings',
  AVAILABILITY = 'availability',
  SCHEDULE = 'schedule',
  PAYMENTS = 'payments',
  FORGOT_PASSWORD = 'forgot-password',
  TEST = 'test',
  ANY = '*',
};

export enum ROUTE_TO {
  ROOT = '/',
  HOME = '/app/home',
  DASHBOARD = '/app/dashboard',
  TEACHERS = '/app/teachers',
  STUDENTS = '/app/students',
  SETTINGS = '/app/settings',
  AVAILABILITY = '/app/availability',
  SCHEDULE = '/app/schedule',
  PAYMENTS = '/app/payments',
  SIGN_IN = '/sign-in',
  SIGN_UP = '/sign-up',
  FORGOT_PASSWORD = '/forgot-password',
  TEST = '/test',
};

export enum NAVIGATE_TO {
  HOME = '#home',
  FEATURES = '#features',
  SERVICES = '#services',
  TESTIMONIALS = '#testimonials',
  CONTACT = '#contact',
};

export enum NAVIGATE_NAME {
  HOME = 'Home',
  FEATURES = 'Features',
  SERVICES = 'Services',
  TESTIMONIALS = 'Testimonials',
  CONTACT = 'Contact',
  SIGN_IN = 'Sign In',
  SIGN_UP = 'sign Up',
  SIGN_OUT = 'sign Out',
  LOGIN = 'Log In',
  LOGOUT = 'Log Out',
  REGISTER = 'Register',
  FORGOT_PASSWORD = 'Forgot password?',
  DASHBOARD = 'Dashboard',
  TEACHERS = 'Teachers',
  STUDENTS = 'Students',
  SETTINGS = 'Settings',
  AVAILABILITY = 'Availability',
  SCHEDULE = 'Schedule',
  PAYMENTS = 'Payments',
};